version: '3.8'
services:
  db_pg_15:
    image: postgres:15
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bestuser
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db_pg_15
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_pg_15:5432/clinic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: bestuser
    ports:
      - "8080:8080"

      
      